### PR TITLE
Initial support for attachments

### PR DESCRIPTION
**Pull request by adzeitor**
Sorry for deleted whitespaces.

### CODE REVIEW

**Comment by akaspin** [comment]
Logic looks good. But why you use strict bytestrings for document body? [`RequestBody`](http://hackage.haskell.org/packages/archive/http-conduit/1.5.0.3/doc/html/Network-HTTP-Conduit.html#t:RequestBody) and `ResumableSource m ByteString` will be much more flexible and efficient.

**Comment by akaspin** [comment]
So. I'm reviewed code. Sorry. It's still not effective and has bugs. For example, by API attachment name _can_ contain unescaped slashes. I will try to implement attachments tomorrow. Thanks for kick :)

UPD: hackage down. A little later. Sorry

**Comment by adzeitor** [comment]
Hmmm, but this test passes

``` haskell
caseJustPutGetSlashes :: Assertion
caseJustPutGetSlashes = bracket_
    setup teardown $
    runCouch conn $ do
      let testContent = "Gandalf Gandalf Gandalf"
      let testContentType = "text/html"

      rev <- couchPut dbName "doc-just" "" [] $ TestDoc "doc" 1 "1"
      _ <- couchPutAttach dbName "doc-just" "src/gandalf.html" rev
              testContentType testContent
      (content, ctype) <- couchGetAttach dbName "doc-just" "src/gandalf.html"
      liftIO $ content @=? testContent
      liftIO $ ctype @=? testContentType

```

**Comment by akaspin** [comment]
Did you see path in db? Try curl.

**Comment by adzeitor** [comment]
Ouch. Now I see.

**Comment by adzeitor** [comment]
I understand what you mean...

couchGetAttach must return conduit source. A function like this

``` haskell
couchGetAttach :: MonadCouch m =>
                  Path             -- ^ Database
                  -> Path           -- ^ Document
                  -> Path           -- ^ Attachment
                  -> m (ResumableSource m B.ByteString, B.ByteString) -- ^ (Content, Content-type)
couchGetAttach db doc att =
  do H.Response _ _ hs bsrc <- couch HT.methodGet
                               (mkAttachPath [db,doc] att)
                               []
                               []
                               (H.RequestBodyBS B.empty)
                               protect'
     let contentType = peekContentType hs
     return (bsrc,contentType)
  where
    peekVal a b = fromJust $ lookup a b
    peekContentType a = peekVal "Content-Type" a
```

**Comment by akaspin** [comment]
@adzeitor. Exactly. Also, `http-conduit` has excellent `RecuestBody`.

**Comment by adzeitor** [comment]
I wrote putAttach using `RequestBodySource`, but it require content length... 
Maybe add contentLength argument?

``` haskell
-- | Upload attachment.
couchPutAttach :: MonadCouch m =>
                  Path             -- ^ Database
                  -> Path           -- ^ Document
                  -> Path           -- ^ Attachment
                  -> Revision       -- ^ Document revision
                  -> B.ByteString   -- ^ Attachent content type
                  -> (Source m B.ByteString)  -- ^ Attachment content
                  -> m Revision
couchPutAttach db doc att rev contentType content =
  do let builderContent = mapOutput (BLB.fromByteString) content
     H.Response _ _ _ bsrc <- couch HT.methodPut
                              (mkAttachPath [db,doc] att)
                              [(HT.hContentType, contentType)]
                              (if rev /= "" then [("rev", Just rev)] else [])
                              (H.RequestBodySource ????? builderContent)
                              protect'
     j <- bsrc $$+- CA.sinkParser A.json
     A.String r <- either throw return $ extractField "rev" j
     return $ TE.encodeUtf8 r

```

**Comment by akaspin** [comment]
@adzeitor. Why not `RequestBody` instead `Source`? It has `RequestBodyLBS`, `RequestBodyBS` and `RequestBodySourceChunked` constructors. And two another with length.

**Comment by akaspin** [comment]
@adzeitor. I'm implement all core commands (see #667417b526ed30be32e33e8971135238f0b0fadc). Sorry, I just hasn't time to make tests.

**Pull request closed without merging**
