### PR TITLE
add getting revision for views and attachments

### PR DESCRIPTION
**Pull request by adzeitor**

### CODE REVIEW

**Comment by adzeitor** [comment]
fix issue with empty view

**Comment by akaspin** [comment]
Code OK. With one exception. It's not ETag. It' revision of view document. Not view result. Try to write some tests.

**Comment by adzeitor** [comment]
You mean revision of design? If so then this is not it.

As I understand it - revision of view changed when result of map changed. Currently this is it. But when map param changed Etag has no change.

**Comment by akaspin** [comment]
Hmm. Very strange. I do a little digging it and got some strange results. Imagine `someview`. Let's go:

```
//db/_design/views/_view/someview
ETag: EGLEL1VG77YWVND02LUP9O9L2   <-- it does not matter
```

Ok. Let's try some query parameters:

```
//db/_design/views/_view/someview?key="somekey"
ETag: EGLEL1VG77YWVND02LUP9O9L2   <-- Err?
```

So. We have two very different requests with very different results. But one `ETag`! I think this is unacceptable. It's issue of CouchDB You can file issue in CouchDB issue tracker. But, until this issue is resolved, it is better not to implement erroneous functionality.

Another two cents... As I understand it, you need to cache requests? But, why not cache the results? Look at [`hedis-pile`](http://hackage.haskell.org/package/hedis-pile-0.6.3) and [`wai-middleware-cache-redis`](http://hackage.haskell.org/package/wai-middleware-cache-redis) packages. The main idea of ​​these packages is to make the cache completely transparent. My company uses them in production.

**Comment by adzeitor** [comment]
Yeah, first I also thinking it was strange.

I think this is not issue, because 

>  An ETag is an opaque identifier assigned by a web server to a specific version of a resource found at a **URL**.
> Comparing ETags only makes sense with respect to one URL—ETags for resources obtained from different URLs may or may not be equal. So no meaning can be inferred from their comparison.
> _from http://en.wikipedia.org/wiki/HTTP_ETag_

and https://issues.apache.org/jira/browse/COUCHDB-1206

In my case browser cache requests(JSON): **URL + ETAG**. For me it works.

Thanks for packages. Currently I'm thinking about in-memory haskell cache (maybe STM).

**Comment by adzeitor** [comment]
Ouch. No function to get rev of staled view :( 

couchViewRevStale ? Or add bool arg?

**Pull request closed without merging**
